version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27070:27070"

  localStack:
    image: localstack/localstack
    container_name: localstack_demo
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8055"
    environment:
      - SERVIVES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  demo-app:
    image: digonil/demo-app:latest
    build: .
    container_name: demo-app
    ports:
      - "8082:8082"