version: '3'
services:
  localStack:
    image: localstack/localstack
    container_name: localstack_demo
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8055"
    environment:
      - SERVIVES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock